#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number
app_user_index:
  path: /user/index
  controller: App\Controller\UserController::new
app_default_index:
  path: /default/index
  controller: App\Controller\DefaultController::new
